export const mockData = [
  {
    id: 1,
    name: 'Valle Jentgens',
    location: 'Manquiring',
    jobTitle: 'Nurse',
    dateStarted: new Date('2025-01-26'),
    numPosts: 10,
    friends: [23, 2, 16, 25, 5, 44],
    tag: 'valle',
    avatar: 'https://i.pravatar.cc/150?u=1',
  },
  {
    id: 2,
    name: 'Vick Roll',
    location: 'Catarina',
    jobTitle: 'Structural Analysis Engineer',
    dateStarted: new Date('2024-06-13'),
    numPosts: 32,
    friends: [22, 48, 35, 35, 36, 28],
    tag: 'vick',
    avatar: 'https://i.pravatar.cc/150?u=2',
  },
  {
    id: 3,
    name: 'Elvyn Gillbey',
    location: 'Aswan',
    jobTitle: 'Electrical Engineer',
    dateStarted: new Date('2025-03-24'),
    numPosts: 26,
    friends: [50, 25, 10, 21, 28, 9],
    tag: 'elvyn',
    avatar: 'https://i.pravatar.cc/150?u=3',
  },
  {
    id: 4,
    name: 'Imogene Boothe',
    location: 'Zlatograd',
    jobTitle: 'Chemical Engineer',
    dateStarted: new Date('2024-05-01'),
    numPosts: 29,
    friends: [49, 27, 28, 32, 13, 18],
    tag: 'imogene',
    avatar: 'https://i.pravatar.cc/150?u=4',
  },
  {
    id: 5,
    name: 'Fiona Downing',
    location: 'Cottbus',
    jobTitle: 'VP Quality Control',
    dateStarted: new Date('2025-03-24'),
    numPosts: 10,
    friends: [49, 21, 16, 34, 30, 44],
    tag: 'fiona',
    avatar: 'https://i.pravatar.cc/150?u=5',
  },
  {
    id: 6,
    name: 'Chandal Giotto',
    location: 'Onsŏng',
    jobTitle: 'Help Desk Operator',
    dateStarted: new Date('2024-07-12'),
    numPosts: 33,
    friends: [48, 38, 47, 8, 12, 43],
    tag: 'chandal',
    avatar: 'https://i.pravatar.cc/150?u=6',
  },
  {
    id: 7,
    name: "Carilyn O'Nowlan",
    location: 'Cansolungon',
    jobTitle: 'Information Systems Manager',
    dateStarted: new Date('2025-04-11'),
    numPosts: 23,
    friends: [50, 19, 38, 24, 24, 2],
    tag: 'carilyn',
    avatar: 'https://i.pravatar.cc/150?u=7',
  },
  {
    id: 8,
    name: 'Saw Rawcliffe',
    location: 'Aix-en-Provence',
    jobTitle: 'Cost Accountant',
    dateStarted: new Date('2024-05-11'),
    numPosts: 20,
    friends: [47, 21, 24, 16, 27, 1],
    tag: 'saw',
    avatar: 'https://i.pravatar.cc/150?u=8',
  },
  {
    id: 9,
    name: 'Barclay McFarlane',
    location: 'Mem Martins',
    jobTitle: 'Staff Scientist',
    dateStarted: new Date('2024-11-21'),
    numPosts: 6,
    friends: [1, 6, 17, 39, 27, 45],
    tag: 'barclay',
    avatar: 'https://i.pravatar.cc/150?u=9',
  },
  {
    id: 10,
    name: 'Benjie Joyes',
    location: 'Xibu',
    jobTitle: 'VP Product Management',
    dateStarted: new Date('2024-08-16'),
    numPosts: 34,
    friends: [36, 50, 29, 50, 21, 44],
    tag: 'benjie',
    avatar: 'https://i.pravatar.cc/150?u=10',
  },
  {
    id: 11,
    name: 'Lilian Haslen',
    location: 'Bahorí',
    jobTitle: 'Executive Secretary',
    dateStarted: new Date('2024-09-03'),
    numPosts: 30,
    friends: [20, 24, 46, 21, 42, 42],
    tag: 'lilian',
    avatar: 'https://i.pravatar.cc/150?u=11',
  },
  {
    id: 12,
    name: 'Isidor Hayers',
    location: 'Venado Tuerto',
    jobTitle: 'Geologist II',
    dateStarted: new Date('2024-07-07'),
    numPosts: 28,
    friends: [3, 14, 43, 29, 16, 37],
    tag: 'isidor',
    avatar: 'https://i.pravatar.cc/150?u=12',
  },
  {
    id: 13,
    name: 'Rem Rattenberie',
    location: 'Jukui',
    jobTitle: 'Analog Circuit Design manager',
    dateStarted: new Date('2024-08-25'),
    numPosts: 28,
    friends: [15, 1, 36, 33, 4, 6],
    tag: 'rem',
    avatar: 'https://i.pravatar.cc/150?u=13',
  },
  {
    id: 14,
    name: 'Sharia Bretelle',
    location: 'Cognac',
    jobTitle: 'Director of Sales',
    dateStarted: new Date('2024-10-29'),
    numPosts: 2,
    friends: [5, 18, 22, 11, 6, 12],
    tag: 'sharia',
    avatar: 'https://i.pravatar.cc/150?u=14',
  },
  {
    id: 15,
    name: 'Elfrida Edward',
    location: 'Shangxian',
    jobTitle: 'Social Worker',
    dateStarted: new Date('2025-04-24'),
    numPosts: 36,
    friends: [49, 39, 9, 39, 33, 46],
    tag: 'elfrida',
    avatar: 'https://i.pravatar.cc/150?u=15',
  },
  {
    id: 16,
    name: 'Kora Weavill',
    location: 'Pandat',
    jobTitle: 'Database Administrator III',
    dateStarted: new Date('2024-09-27'),
    numPosts: 29,
    friends: [6, 22, 19, 25, 12, 18],
    tag: 'kora',
    avatar: 'https://i.pravatar.cc/150?u=16',
  },
  {
    id: 17,
    name: 'Urbanus Younghusband',
    location: 'Asahikawa',
    jobTitle: 'Administrative Assistant II',
    dateStarted: new Date('2025-01-20'),
    numPosts: 4,
    friends: [4, 31, 46, 37, 40, 31],
    tag: 'urbanus',
    avatar: 'https://i.pravatar.cc/150?u=17',
  },
  {
    id: 18,
    name: 'Dene Hollow',
    location: 'Ḩajjah',
    jobTitle: 'Geological Engineer',
    dateStarted: new Date('2024-05-20'),
    numPosts: 23,
    friends: [5, 33, 28, 25, 14, 28],
    tag: 'dene',
    avatar: 'https://i.pravatar.cc/150?u=18',
  },
  {
    id: 19,
    name: 'Kippy Dane',
    location: 'Shangfang',
    jobTitle: 'Financial Analyst',
    dateStarted: new Date('2024-09-28'),
    numPosts: 21,
    friends: [7, 11, 3, 15, 47, 28],
    tag: 'kippy',
    avatar: 'https://i.pravatar.cc/150?u=19',
  },
  {
    id: 20,
    name: 'Etti Lathleiffure',
    location: 'Knivsta',
    jobTitle: 'Administrative Assistant III',
    dateStarted: new Date('2024-10-16'),
    numPosts: 26,
    friends: [8, 17, 30, 8, 47, 30],
    tag: 'etti',
    avatar: 'https://i.pravatar.cc/150?u=20',
  },
  {
    id: 21,
    name: 'Hermia Malpas',
    location: 'Dongting',
    jobTitle: 'Associate Professor',
    dateStarted: new Date('2024-08-19'),
    numPosts: 6,
    friends: [46, 22, 42, 3, 28, 9],
    tag: 'hermia',
    avatar: 'https://i.pravatar.cc/150?u=21',
  },
  {
    id: 22,
    name: 'Cesaro Price',
    location: 'Yalukou',
    jobTitle: 'Quality Control Specialist',
    dateStarted: new Date('2024-09-18'),
    numPosts: 22,
    friends: [14, 25, 18, 9, 42, 7],
    tag: 'cesaro',
    avatar: 'https://i.pravatar.cc/150?u=22',
  },
  {
    id: 23,
    name: 'Wolfy Vatcher',
    location: 'Longquan',
    jobTitle: 'Physical Therapy Assistant',
    dateStarted: new Date('2024-12-17'),
    numPosts: 11,
    friends: [7, 48, 19, 2, 24, 30],
    tag: 'wolfy',
    avatar: 'https://i.pravatar.cc/150?u=23',
  },
  {
    id: 24,
    name: 'Kin Dawson',
    location: 'Guadalupe',
    jobTitle: 'Financial Advisor',
    dateStarted: new Date('2024-05-13'),
    numPosts: 30,
    friends: [4, 48, 40, 35, 48, 21],
    tag: 'kin',
    avatar: 'https://i.pravatar.cc/150?u=24',
  },
  {
    id: 25,
    name: 'Lambert Shimuk',
    location: 'Yuhuang',
    jobTitle: 'Data Coordinator',
    dateStarted: new Date('2024-07-24'),
    numPosts: 18,
    friends: [31, 15, 39, 37, 5, 37],
    tag: 'lambert',
    avatar: 'https://i.pravatar.cc/150?u=25',
  },
  {
    id: 26,
    name: 'Auberta Barnewelle',
    location: 'Ourentã',
    jobTitle: 'Developer III',
    dateStarted: new Date('2025-03-04'),
    numPosts: 39,
    friends: [21, 25, 20, 40, 16, 3],
    tag: 'auberta',
    avatar: 'https://i.pravatar.cc/150?u=26',
  },
  {
    id: 27,
    name: 'Donia Mullin',
    location: 'Ipatinga',
    jobTitle: 'Design Engineer',
    dateStarted: new Date('2024-12-27'),
    numPosts: 17,
    friends: [37, 16, 50, 15, 42, 43],
    tag: 'donia',
    avatar: 'https://i.pravatar.cc/150?u=27',
  },
  {
    id: 28,
    name: 'Kilian Izhaky',
    location: 'Villa del Rosario',
    jobTitle: 'Director of Sales',
    dateStarted: new Date('2025-03-09'),
    numPosts: 6,
    friends: [31, 29, 24, 40, 24, 48],
    tag: 'kilian',
    avatar: 'https://i.pravatar.cc/150?u=28',
  },
  {
    id: 29,
    name: 'Harvey Stookes',
    location: 'Haixing',
    jobTitle: 'Recruiting Manager',
    dateStarted: new Date('2025-01-13'),
    numPosts: 4,
    friends: [3, 3, 24, 31, 11, 3],
    tag: 'harvey',
    avatar: 'https://i.pravatar.cc/150?u=29',
  },
  {
    id: 30,
    name: 'Eryn Ockland',
    location: 'Hecheng',
    jobTitle: 'Safety Technician IV',
    dateStarted: new Date('2025-03-15'),
    numPosts: 35,
    friends: [19, 15, 38, 21, 39, 25],
    tag: 'eryn',
    avatar: 'https://i.pravatar.cc/150?u=30',
  },
  {
    id: 31,
    name: 'Jaimie Vedeniktov',
    location: 'Mengxingzhuang',
    jobTitle: 'Environmental Tech',
    dateStarted: new Date('2025-03-15'),
    numPosts: 31,
    friends: [12, 20, 33, 18, 37, 33],
    tag: 'jaimie',
    avatar: 'https://i.pravatar.cc/150?u=31',
  },
  {
    id: 32,
    name: 'Roy Kirsche',
    location: 'Carumas',
    jobTitle: 'GIS Technical Architect',
    dateStarted: new Date('2024-08-06'),
    numPosts: 31,
    friends: [35, 8, 30, 22, 47, 28],
    tag: 'roy',
    avatar: 'https://i.pravatar.cc/150?u=32',
  },
  {
    id: 33,
    name: 'Karlens Joiner',
    location: 'Shagonar',
    jobTitle: 'Pharmacist',
    dateStarted: new Date('2024-07-10'),
    numPosts: 8,
    friends: [4, 44, 39, 46, 40, 48],
    tag: 'karlens',
    avatar: 'https://i.pravatar.cc/150?u=33',
  },
  {
    id: 34,
    name: 'Glyn Daysh',
    location: 'Arneiro',
    jobTitle: 'Software Consultant',
    dateStarted: new Date('2024-07-08'),
    numPosts: 9,
    friends: [29, 38, 4, 46, 14, 32],
    tag: 'glyn',
    avatar: 'https://i.pravatar.cc/150?u=34',
  },
  {
    id: 35,
    name: 'Douglas Jaine',
    location: 'Cikadongdong',
    jobTitle: 'Mechanical Systems Engineer',
    dateStarted: new Date('2025-01-14'),
    numPosts: 7,
    friends: [16, 9, 12, 5, 3, 19],
    tag: 'douglas',
    avatar: 'https://i.pravatar.cc/150?u=35',
  },
  {
    id: 36,
    name: 'Aurelea Bursell',
    location: 'Kota Kinabalu',
    jobTitle: 'Assistant Professor',
    dateStarted: new Date('2025-04-19'),
    numPosts: 23,
    friends: [17, 45, 15, 16, 14, 41],
    tag: 'aurelea',
    avatar: 'https://i.pravatar.cc/150?u=36',
  },
  {
    id: 37,
    name: 'Harriott Overstone',
    location: 'Primorsko',
    jobTitle: 'Biostatistician IV',
    dateStarted: new Date('2024-07-05'),
    numPosts: 19,
    friends: [9, 15, 31, 10, 16, 30],
    tag: 'harriott',
    avatar: 'https://i.pravatar.cc/150?u=37',
  },
  {
    id: 38,
    name: 'Enriqueta Lyptratt',
    location: 'Houjiachuan',
    jobTitle: 'Actuary',
    dateStarted: new Date('2024-10-10'),
    numPosts: 14,
    friends: [30, 16, 34, 27, 48, 32],
    tag: 'enriqueta',
    avatar: 'https://i.pravatar.cc/150?u=38',
  },
  {
    id: 39,
    name: 'Genna Attarge',
    location: 'Kalapagenep',
    jobTitle: 'Social Worker',
    dateStarted: new Date('2024-12-12'),
    numPosts: 31,
    friends: [2, 5, 2, 7, 50, 17],
    tag: 'genna',
    avatar: 'https://i.pravatar.cc/150?u=39',
  },
  {
    id: 40,
    name: 'Amaleta Staples',
    location: 'Chishui',
    jobTitle: 'Marketing Assistant',
    dateStarted: new Date('2024-06-29'),
    numPosts: 9,
    friends: [29, 24, 43, 22, 29, 34],
    tag: 'amaleta',
    avatar: 'https://i.pravatar.cc/150?u=40',
  },
  {
    id: 41,
    name: 'Cart Sweedy',
    location: 'Xiancun',
    jobTitle: 'Marketing Manager',
    dateStarted: new Date('2024-10-28'),
    numPosts: 39,
    friends: [18, 19, 30, 23, 48, 29],
    tag: 'cart',
    avatar: 'https://i.pravatar.cc/150?u=41',
  },
  {
    id: 42,
    name: 'Loralee Pimmocke',
    location: 'Guandu',
    jobTitle: 'VP Sales',
    dateStarted: new Date('2024-07-05'),
    numPosts: 34,
    friends: [37, 46, 41, 23, 5, 10],
    tag: 'loralee',
    avatar: 'https://i.pravatar.cc/150?u=42',
  },
  {
    id: 43,
    name: "Tabbie O'Cooney",
    location: 'Jianping',
    jobTitle: 'Engineer I',
    dateStarted: new Date('2024-05-09'),
    numPosts: 16,
    friends: [6, 12, 18, 29, 18, 28],
    tag: 'tabbie',
    avatar: 'https://i.pravatar.cc/150?u=43',
  },
  {
    id: 44,
    name: 'Tallou Speares',
    location: 'Santa Venera',
    jobTitle: 'Structural Engineer',
    dateStarted: new Date('2024-10-26'),
    numPosts: 31,
    friends: [49, 41, 15, 46, 5, 24],
    tag: 'tallou',
    avatar: 'https://i.pravatar.cc/150?u=44',
  },
  {
    id: 45,
    name: 'Shermie Dragonette',
    location: 'Arbais',
    jobTitle: 'Librarian',
    dateStarted: new Date('2024-08-01'),
    numPosts: 30,
    friends: [1, 8, 38, 8, 18, 36],
    tag: 'shermie',
    avatar: 'https://i.pravatar.cc/150?u=45',
  },
  {
    id: 46,
    name: 'Magdalena Olenikov',
    location: 'Pardelhas',
    jobTitle: 'Assistant Professor',
    dateStarted: new Date('2024-06-19'),
    numPosts: 20,
    friends: [49, 40, 33, 18, 30, 23],
    tag: 'magdalena',
    avatar: 'https://i.pravatar.cc/150?u=46',
  },
  {
    id: 47,
    name: 'Laetitia Dudliston',
    location: 'Ōtsu-shi',
    jobTitle: 'Senior Cost Accountant',
    dateStarted: new Date('2024-08-06'),
    numPosts: 11,
    friends: [2, 7, 45, 6, 30, 13],
    tag: 'laetitia',
    avatar: 'https://i.pravatar.cc/150?u=47',
  },
  {
    id: 48,
    name: 'Papageno Dumbar',
    location: 'České Meziříčí',
    jobTitle: 'Sales Representative',
    dateStarted: new Date('2025-03-17'),
    numPosts: 31,
    friends: [49, 15, 25, 47, 50, 14],
    tag: 'papageno',
    avatar: 'https://i.pravatar.cc/150?u=48',
  },
  {
    id: 49,
    name: 'Gabriel Stapells',
    location: 'Głuchołazy',
    jobTitle: 'Nuclear Power Engineer',
    dateStarted: new Date('2024-05-26'),
    numPosts: 30,
    friends: [16, 28, 13, 2, 33, 36],
    tag: 'gabriel',
    avatar: 'https://i.pravatar.cc/150?u=49',
  },
  {
    id: 50,
    name: 'Laurens Cracknall',
    location: 'Peruc',
    jobTitle: 'Senior Quality Engineer',
    dateStarted: new Date('2024-12-17'),
    numPosts: 25,
    friends: [33, 16, 5, 28, 10, 46],
    tag: 'laurens',
    avatar: 'https://i.pravatar.cc/150?u=50',
  },
];
